{
 "title": "Crud",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Quantile 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{uri=~\"/users/.*|/users(|/[0-9]+)\", method=~\"GET|POST|PUT|DELETE\"}[10m])) by (le, method)) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\"/users/.*|/users(|/[0-9]+)\", method=~\"GET|POST|PUT|DELETE\"}[10m])) by (le, method)) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\"/users/.*|/users(|/[0-9]+)\", method=~\"GET|POST|PUT|DELETE\"}[10m])) by (le, method)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/users/.*|/users(|/[0-9]+)\", method=~\"GET|POST|PUT|DELETE\"}[10m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/users/.*|/users(|/[0-9]+)\", method=~\"GET|POST|PUT|DELETE\", status=\"500\"}[10m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress quantile 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[10m])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[10m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress quantile 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[10m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress 500 error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[10m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}