apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    env: healthcheck-app-prod
#    env: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000