apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    app: {{ .Release.Name }}
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: {{ .Release.Name }}